# Generated by Django 4.2.1 on 2023-05-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_client_movieclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='available_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
