# Generated by Django 4.2.1 on 2023-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_movies_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='available_copies',
            field=models.IntegerField(default=0),
        ),
    ]
