# Generated by Django 4.2.1 on 2023-05-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_client_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
