# Generated by Django 4.2.1 on 2023-05-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_movies_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address_line1',
            new_name='address_line',
        ),
    ]
